linters:
  enable:
    - gocritic
    - gofmt
    - goimports
    - govet
    - staticcheck
    - errcheck
    - gocyclo
    - ineffassign
    - gosimple
    - gocognit
  enable-all: false
  disable:
    - dupl
    - maligned
    - scopelint
    - structcheck
    - varcheck

  presets:
    - bugs
    - error
    - format
    - performance
    - style
    - test

  fast: true

issues:
  exclude:
    - "abcdef"

  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck

    - path: internal/hmac/
      text: "weak cryptographic primitive"
      linters:
        - gosec

    - linters:
        - staticcheck
      text: "SA9003:"

    - linters:
        - lll
      source: "^//go:generate "

  exclude-generated: strict

  max-issues-per-linter: 50

  new: true
  new-from-rev: HEAD

  fix: true

severity:
  default-severity: error

  case-sensitive: false

  rules:
    - linters:
        - dupl
      severity: info
    - linters:
        - gofmt
      severity: warning
