apiVersion: v1
data:
  ACCESS_TOKEN_EXPIRE: "877"
  ADDRESS: 0.0.0.0
  ENVIRONMENT: local
  HEADER_TIMEOUT: 5s
  JWT_TOKEN_SECRET: my_secret_key
  POSTGRES_DB: postgres
  POSTGRES_HOST: postgres
  POSTGRES_MAX_CONNECTIONS: "20"
  POSTGRES_PORT: "5432"
  POSTGRES_TIMEOUT: "30"
  POSTGRES_USER: postgres
  REDIS_DATABASE: "0"
  REDIS_HOST: redis
  REDIS_POOL_SIZE: "10"
  REDIS_PORT: "6379"
  REDIS_TIMEOUT: "10"
  REDIS_TTL: "5"
  REST_PORT: "8080"
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: app-local-env
  name: local-env
