apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    app: {{ .Release.Name }}-postgres
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o kubermanifests.yaml
    kompose.version: 1.34.0 (cbf2835db)
spec:
  ports:
    - name: "5432"
      port: {{ .Values.env.POSTGRES_PORT }}
      targetPort: {{ .Values.env.POSTGRES_PORT }}
  selector:
    app: {{ .Release.Name }}-postgres
