apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-redis-secret
  labels:
    app: {{ .Release.Name }}-redis-secret
type: Opaque
data:
  REDIS_PASSWORD: {{ .Values.env.REDIS_PASSWORD | b64enc }}
